// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: fractal.proto

package fractal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FractalType   string                 `protobuf:"bytes,1,opt,name=fractal_type,json=fractalType,proto3" json:"fractal_type,omitempty"`
	RealMin       float64                `protobuf:"fixed64,2,opt,name=real_min,json=realMin,proto3" json:"real_min,omitempty"`
	RealMax       float64                `protobuf:"fixed64,3,opt,name=real_max,json=realMax,proto3" json:"real_max,omitempty"`
	ImagMin       float64                `protobuf:"fixed64,4,opt,name=imag_min,json=imagMin,proto3" json:"imag_min,omitempty"`
	ImagMax       float64                `protobuf:"fixed64,5,opt,name=imag_max,json=imagMax,proto3" json:"imag_max,omitempty"`
	PixelWidth    int32                  `protobuf:"varint,6,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight   int32                  `protobuf:"varint,7,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	MaxIterations int32                  `protobuf:"varint,8,opt,name=max_iterations,json=maxIterations,proto3" json:"max_iterations,omitempty"`
	BlockId       string                 `protobuf:"bytes,9,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeRequest) Reset() {
	*x = ComputeRequest{}
	mi := &file_fractal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeRequest) ProtoMessage() {}

func (x *ComputeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fractal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeRequest.ProtoReflect.Descriptor instead.
func (*ComputeRequest) Descriptor() ([]byte, []int) {
	return file_fractal_proto_rawDescGZIP(), []int{0}
}

func (x *ComputeRequest) GetFractalType() string {
	if x != nil {
		return x.FractalType
	}
	return ""
}

func (x *ComputeRequest) GetRealMin() float64 {
	if x != nil {
		return x.RealMin
	}
	return 0
}

func (x *ComputeRequest) GetRealMax() float64 {
	if x != nil {
		return x.RealMax
	}
	return 0
}

func (x *ComputeRequest) GetImagMin() float64 {
	if x != nil {
		return x.ImagMin
	}
	return 0
}

func (x *ComputeRequest) GetImagMax() float64 {
	if x != nil {
		return x.ImagMax
	}
	return 0
}

func (x *ComputeRequest) GetPixelWidth() int32 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *ComputeRequest) GetPixelHeight() int32 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

func (x *ComputeRequest) GetMaxIterations() int32 {
	if x != nil {
		return x.MaxIterations
	}
	return 0
}

func (x *ComputeRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

type ComputeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Iterations    []uint32               `protobuf:"varint,2,rep,packed,name=iterations,proto3" json:"iterations,omitempty"`
	PixelWidth    int32                  `protobuf:"varint,3,opt,name=pixel_width,json=pixelWidth,proto3" json:"pixel_width,omitempty"`
	PixelHeight   int32                  `protobuf:"varint,4,opt,name=pixel_height,json=pixelHeight,proto3" json:"pixel_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeResponse) Reset() {
	*x = ComputeResponse{}
	mi := &file_fractal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeResponse) ProtoMessage() {}

func (x *ComputeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fractal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeResponse.ProtoReflect.Descriptor instead.
func (*ComputeResponse) Descriptor() ([]byte, []int) {
	return file_fractal_proto_rawDescGZIP(), []int{1}
}

func (x *ComputeResponse) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ComputeResponse) GetIterations() []uint32 {
	if x != nil {
		return x.Iterations
	}
	return nil
}

func (x *ComputeResponse) GetPixelWidth() int32 {
	if x != nil {
		return x.PixelWidth
	}
	return 0
}

func (x *ComputeResponse) GetPixelHeight() int32 {
	if x != nil {
		return x.PixelHeight
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_fractal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fractal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_fractal_proto_rawDescGZIP(), []int{2}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_fractal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fractal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_fractal_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_fractal_proto protoreflect.FileDescriptor

const file_fractal_proto_rawDesc = "" +
	"\n" +
	"\rfractal.proto\x12\afractal\"\xa5\x02\n" +
	"\x0eComputeRequest\x12!\n" +
	"\ffractal_type\x18\x01 \x01(\tR\vfractalType\x12\x19\n" +
	"\breal_min\x18\x02 \x01(\x01R\arealMin\x12\x19\n" +
	"\breal_max\x18\x03 \x01(\x01R\arealMax\x12\x19\n" +
	"\bimag_min\x18\x04 \x01(\x01R\aimagMin\x12\x19\n" +
	"\bimag_max\x18\x05 \x01(\x01R\aimagMax\x12\x1f\n" +
	"\vpixel_width\x18\x06 \x01(\x05R\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\a \x01(\x05R\vpixelHeight\x12%\n" +
	"\x0emax_iterations\x18\b \x01(\x05R\rmaxIterations\x12\x19\n" +
	"\bblock_id\x18\t \x01(\tR\ablockId\"\x90\x01\n" +
	"\x0fComputeResponse\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1e\n" +
	"\n" +
	"iterations\x18\x02 \x03(\rR\n" +
	"iterations\x12\x1f\n" +
	"\vpixel_width\x18\x03 \x01(\x05R\n" +
	"pixelWidth\x12!\n" +
	"\fpixel_height\x18\x04 \x01(\x05R\vpixelHeight\"\x12\n" +
	"\x10HeartbeatRequest\"-\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy2\x91\x01\n" +
	"\rFractalWorker\x12<\n" +
	"\aCompute\x12\x17.fractal.ComputeRequest\x1a\x18.fractal.ComputeResponse\x12B\n" +
	"\tHeartbeat\x12\x19.fractal.HeartbeatRequest\x1a\x1a.fractal.HeartbeatResponseB&Z$fractal-cluster/internal/gen/fractalb\x06proto3"

var (
	file_fractal_proto_rawDescOnce sync.Once
	file_fractal_proto_rawDescData []byte
)

func file_fractal_proto_rawDescGZIP() []byte {
	file_fractal_proto_rawDescOnce.Do(func() {
		file_fractal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fractal_proto_rawDesc), len(file_fractal_proto_rawDesc)))
	})
	return file_fractal_proto_rawDescData
}

var file_fractal_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_fractal_proto_goTypes = []any{
	(*ComputeRequest)(nil),    // 0: fractal.ComputeRequest
	(*ComputeResponse)(nil),   // 1: fractal.ComputeResponse
	(*HeartbeatRequest)(nil),  // 2: fractal.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 3: fractal.HeartbeatResponse
}
var file_fractal_proto_depIdxs = []int32{
	0, // 0: fractal.FractalWorker.Compute:input_type -> fractal.ComputeRequest
	2, // 1: fractal.FractalWorker.Heartbeat:input_type -> fractal.HeartbeatRequest
	1, // 2: fractal.FractalWorker.Compute:output_type -> fractal.ComputeResponse
	3, // 3: fractal.FractalWorker.Heartbeat:output_type -> fractal.HeartbeatResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fractal_proto_init() }
func file_fractal_proto_init() {
	if File_fractal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fractal_proto_rawDesc), len(file_fractal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fractal_proto_goTypes,
		DependencyIndexes: file_fractal_proto_depIdxs,
		MessageInfos:      file_fractal_proto_msgTypes,
	}.Build()
	File_fractal_proto = out.File
	file_fractal_proto_goTypes = nil
	file_fractal_proto_depIdxs = nil
}
